### ISSUE TITLE
How can i stub it in tests?

### ISSUE THREAD

**Issue by blacksonic** [sindresorhus/delay#14]
When I use the library how can I fake the delay and instead of waiting return an instantly resolving Promise?

**Comment by SamVerschueren** [comment]
Not sure if I understand what you mean. Can you elaborate a little bit more?

**Comment by blacksonic** [comment]
I have a method where i use this package.
I want to test it, but don't want the code to wait for the delay, that is why I want to mock/stub it.

**Comment by SamVerschueren** [comment]
[proxyquire](https://github.com/thlorenz/proxyquire) could help you achieve that.

**Comment by sindresorhus** [comment]
I would use http://sinonjs.org/docs/#clock
