### ISSUE TITLE
Cancelation?

### ISSUE THREAD

**Issue by timdp** [sindresorhus/delay#15]
I know there's currently a whole debate about cancelable promises and such, but at any rate, there's currently no way to clear the timeout that `delay` sets. Has the possibility of introducing a cancelation function for this been considered yet?

**Comment by sindresorhus** [comment]
Yup. Totally open to a pull request. I've just haven't needed it yet personally.

Easiest would be to just add an `.abort()` method. Like: https://github.com/sindresorhus/p-throttle/commit/6ebf67a86b6f51cc0fe761d1a240534f9f48d945

**Comment by timdp** [comment]
Cool, I'll try to make some time!

**Comment by sindresorhus** [comment]
Fixed by #17.
