### ISSUE TITLE
bablified distributable 

### ISSUE THREAD

**Issue by drcmda** [sindresorhus/delay#18]
This dependency currently crashes webpacks uglify if exclude "node_modules" is given, which most projects still seem to do. It would be nice if it had a bablified distributable.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
