### ISSUE TITLE
Unexpected token: name (CancelError)

### ISSUE THREAD

**Issue by wub** [sindresorhus/delay#20]
With production settings, uglify gives me this error, which points at `delay`:

```
Message: Unexpected token: name (CancelError)
File: /dist/ssr.js
Line number: 1516
Column number: 6
Source error:

Line 1516: class CancelError extends Error {
----------------^
Line 1517:     constructor(message) {
```

The comment by @yudao in this thread lead me here, I assume it's the same problem: https://github.com/brunch/brunch/issues/1715

Is this because Uglify can't speak ES6 yet?

If so, I'll try one of these when I have time:

- https://www.npmjs.com/package/uglify-es
- https://github.com/babel/minify

**Comment by wub** [comment]
Does this mean that I'm shipping code with `class` in it to browsers? This might bite a few other people that have `node_modules` ignored for compilation.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
