### ISSUE TITLE
.then(delay(ms)) no longer working again

### ISSUE THREAD

**Issue by olsonpm** [sindresorhus/delay#22]
Same issue as #1, brought back by commit 90d16f2

I will create a PR assuming you still want this functionality.  Honestly I only looked at the code base after reading `delay(ms)` behaves differently from `.then(delay(ms))` in the docs.  Personally I would prefer to have `delay(ms)` return a promise always, and to allow users to wrap it if needed e.g. `.then(res => delay(ms, res))`.

Your library though :)

**Comment by sindresorhus** [comment]
Yes, I want to remove `.then(delay(ms))`. See: https://github.com/sindresorhus/delay/issues/21 Pull request welcome :)

**Comment by olsonpm** [comment]
Oh I saw that, didn't realize "thunk api" was referring to that functionality.  I'll work on that.
