### ISSUE TITLE
Does not precompile ES6 features to ES5 - breaks build, fails to minify

### ISSUE THREAD

**Issue by Monichre** [sindresorhus/delay#28]

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
