### ISSUE TITLE
Allow to change the promise result when calling clear

### ISSUE THREAD

**Issue by Congelli501** [sindresorhus/delay#36]
It would be nice to add a non mandatory parameter to clear(), to change the result of the delay() promise.

The main purpose would be to allow the code running after a delay() to behave differently if the delay was cleared (like doing nothing, if the user want to cancel the scheduled work).

As clear doesn't accept any parameter, the change would be backward compatible.

**Comment by sindresorhus** [comment]
I'm gonna pass on this as it doesn't have much use with async/await as you can just return a new value yourself.
