### ISSUE TITLE
Factory method to create delay implementation with bound timer methods

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/delay#39]
It'd be useful if I could do the following:

```js
import { factory } from 'delay'

const delay = factory({ setTimeout, clearTimeout })
```

Since this binds the implementation to the timer methods I've provided, I can then safely stub the timers using say `lolex` and still use the `delay` interface.

**Comment by sindresorhus** [comment]
Sure

**Comment by Torgen** [comment]
This breaks using sinon.useFakeTimers(), as setTimeout and cancelTimeout are captured before sinon can stub them out.

**Comment by novemberborn** [comment]
> This breaks using sinon.useFakeTimers(), as setTimeout and cancelTimeout are captured before sinon can stub them out.

That's kinda the point of this feature. It should only be used though when you're actively trying to avoid stubbing.

**Comment by Torgen** [comment]
You can't not use this feature, is the problem, because the default version
of delay also uses the factory method.

**Comment by novemberborn** [comment]
No it should use the global methods by default.

**Comment by Torgen** [comment]
It grabs the value of setTimeout and clearTimeout once when the module is
loaded, so it doesn't notice if you replace their values from the test
harness.

**Comment by novemberborn** [comment]
Ah of course, thanks for pointing that out! Yea that's not what I intended. Probably best to open a new issue for that. I'm sure @sindresorhus would appreciate a PR as well if you have some thoughts on how to fix this.
