### ISSUE TITLE
Add `.range()` method

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/delay#50]
See https://github.com/sindresorhus/delay/pull/47

**Comment by fregante** [comment]
I don't get this. Why would you want a **random** timeout? Do you want your tests to randomly fail?

**Comment by sindresorhus** [comment]
@fregante It's only random within a range. It can be useful to not produce predictable results. For example, spam detectors can detect when something takes the same amount every time. It can also help catch ordering issues since the time is not constant.

**Comment by fregante** [comment]
This sounds like a very specific situation that could easily be solved without an extension:

```diff
- delay.random(100, 300)
+ delay(100 + 200 * Math.random())
```

What if I need `delay` to take longer in production? Are we gonna add an `env` extension?

```js
delay.if(isProd, 300, 100)
```

**Comment by sindresorhus** [comment]
You are kind of proving the use-case though as `100 + 200 * Math.random()` is not a good way to do range random. It will result in bias.

https://github.com/sindresorhus/delay/blob/bcfc9659eb7fbe5e47a6a60b80857c873eb77e2c/index.js#L3-L4

**Comment by sindresorhus** [comment]
As for a specific use-case, in https://github.com/sindresorhus/p-map/blob/master/test.js, I do a lot of delay-based tests and having hard-coded times might miss timing issues.
