### ISSUE TITLE
Support waiting until date

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/delay#52]
It would be useful if delay allowed waiting until a specific date. This is useful for timers, schedulers and cron jobs.

```js
const delay = require('delay');

await delay.date(date)
```

// @sindresorhus

**Comment by sindresorhus** [comment]
That's outside the scope of this package. Sounds like a good idea for a separate package. You could even include some user-friendly syntax/DSL for scheduling and repeated scheduling.
