### ISSUE TITLE
delay.reject()

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/delay#7]
Idea from: https://github.com/ariporad/ava/blob/c7b0154f8ae181e892d58ab1d50aee6154a9a743/test/test.js#L7-L12

```js
delay.reject(100, 'message');
delay.reject(100, new Error('message')); // equivalent to the above
```

If a string, it's converted to an `Error`, otherwise passed through.

I know the first case is not like `Promise.reject()`, but is there any good reason not to reject with an error?

@ariporad @jamestalmage Do you think it would be useful to have this here?

**Comment by ariporad** [comment]
Absolutely. Shall I submit a PR?

**Comment by ariporad** [comment]
Absolutely. I think this wouldn't be hard to add, and would be rather useful. However, I think that if we were to add this we should also do `delay.resolve`, and not do the error conversion thing (that makes sense in the context of those AVA tests, but not really in general).

I'm happy to submit a PR if you want.

**Comment by sindresorhus** [comment]
> However, I think that if we were to add this we should also do delay.resolve

Why? Do you need it for something? I kinda like how I can just write `delay()`, which is the 95% use-case. `.reject()` is just an added bonus.

**Comment by ariporad** [comment]
Completeness. It would be strange to have one and not the other. Plus, it's really trivial to write.

**Comment by sindresorhus** [comment]
But now you have two ways of doing the same thing, which I'm not a big fan of. I usually have one default export for the main use-case and then if there's any nice-to-haves, they're put as methods.

**Comment by sindresorhus** [comment]
> and not do the error conversion thing (that makes sense in the context of those AVA tests, but not really in general).

Why do think we shouldn't do it? Most will use `new Error()`, so I thought it would be nice to make the main use-case simpler. And also prevent anyone from shooting themselves in the foot and rejecting a string or something non-error. I think `Promise.reject()` only supports this for consistency with `throw`. I don't see why we can't improve the IMHO broken default behavior.

**Comment by ariporad** [comment]
In regard to the two-ways to do something: Sometimes its worth a little redundancy to avoid confusion down the road.

Imagine that six months ago you wrote the following code:

```javascript
var delay = require('delay');

// ...

return delay.reject(1000, new Error('foo'));
```

Without looking at the docs, you'd assume that you can use `delay.reject`. Now imagine that you're in the same file, and you see this:

```javascript
// FIXME: every once in a while, this resolves before the promise from #doSomethingElse, and causes problems.
return Promise.reject('foo');
```

You'd assume that you could just do this:


```javascript
// FIXME: every once in a while, this resolves before the promise from #doSomethingElse, and causes problems.
return delay.reject(10, 'foo');
```

**Comment by sindresorhus** [comment]
Ok, how about we add it undocumented then?

**Comment by jamestalmage** [comment]
I am :+1: for the idea. Not sure where i stand on the string to error conversion. Seems a little magic. Also, this is primarily for testing - and if I am accepting user generated promises in my API, correctly handling non-error rejections is a something I want to test.

**Comment by ariporad** [comment]
Here's three reasons why I wouldn't do that:
1. Then they'll have to go digging in the source code to figure out why
their string is being cast to a promise
2. If it's not documented, it doesn't exist. Semver doesn't apply. Don't
use it.
3. No.

**Comment by jamestalmage** [comment]
:-1: for resolve. Keep it simple.

**Comment by sindresorhus** [comment]
Ok. No `.resolve()` (sorry @ariporad, but I'm an extreme minimalist) and no magic string to error conversion. PR welcome :)

**Comment by jamestalmage** [comment]
What should we do if used like this:

```js
someprise.then(delay.reject(100));

someprise.then(delay.reject(100, new Error()));
```

**Comment by sindresorhus** [comment]
@jamestalmage Same as `Promise.reject()` I assume? Or do you have a better suggestion?

**Comment by jamestalmage** [comment]
With `delay` we just delay and then pass through the result. I think `delay.reject(100)`  with only one arg should delay and reject with whatever it was called with.

You can then do:

```js
somePromise.then(delay(100), delay.reject(100))
```

To delay resolution and rejection

**Comment by ariporad** [comment]
@sindresorhus, @jamestalmage: That doesn't make any sense though, it would just return a promise. We have no way to know how it's being used.

**Comment by ariporad** [comment]
Never mind. That makes sense.

**Comment by ariporad** [comment]
When I'm home in an hour or so I'll submit a PR

**Comment by sindresorhus** [comment]
:+1: Good idea.
